# Generated by Django 4.2.4 on 2023-10-29 17:07

from django.db import migrations, models
import pd.models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='id',
        ),
        migrations.AddField(
            model_name='filedata',
            name='pk_name_location',
            field=models.CharField(default=pd.models.generate_default_pk_name_location, max_length=510, primary_key=True, serialize=False),
        ),
    ]
