# Generated by Django 4.2.4 on 2023-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0003_folderdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderdata',
            name='files',
        ),
        migrations.AddField(
            model_name='folderdata',
            name='files',
            field=models.ManyToManyField(to='pd.filedata'),
        ),
    ]
