# Generated by Django 4.2.1 on 2023-09-26 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_drive_url_path', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MIS_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgFrtDiffName', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('staff_last_name', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('staff_id', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('department', models.CharField(choices=[('OBHS', 'OBHS'), ('Electrical', 'Electrical')], default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(blank=True, default=None, null=True)),
                ('Type', models.CharField(choices=[('RNCC', 'RNCC'), ('RGD', 'RGD'), ('DNR', 'DNR'), ('PNBE', 'PNBE'), ('PPTA', 'PPTA'), ('IPR', 'IPR'), ('KEU', 'KEU'), ('MKA', 'MKA'), ('ARA', 'ARA')], default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Data_Upload',
            fields=[
                ('unique_id', models.FloatField(blank=True, default=None, null=True)),
                ('sl_number', models.CharField(blank=True, default='-1', max_length=100, null=True)),
                ('reference_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('closing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('disposal_time', models.FloatField(blank=True, default=None, null=True)),
                ('mode', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('train_station', models.FloatField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('channel', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('Type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rake_number', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('staff_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('staff_id', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('problem_type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sub_type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('commodity', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('zone', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('div', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('breach', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rating', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('complaint_discription', models.TextField(blank=True, default=None, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('number_of_time_forwarded', models.FloatField(blank=True, default=None, null=True)),
                ('pnr_utc_number', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('train_coach_number', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('feedback_remark', models.TextField(blank=True, default=None, null=True)),
                ('upcoming_station', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mobile_number_or_email', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('current_user_mobile_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('train_coach_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('physical_coach_number', models.FloatField(blank=True, default=0.0, null=True)),
                ('physical_coach_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('train_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('owning_zone', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('owning_div', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('current_user_id', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('current_user_phone_number', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('dept', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
