# Generated by Django 4.2.1 on 2023-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.AddField(
            model_name='device',
            name='passw',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uname',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
